spring.application.name=ems

server.port=9191

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${EMS_DB_URL}
spring.datasource.username=${EMS_DB_USERNAME}
spring.datasource.password=${EMS_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true